import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Button, Card, Col, Descriptions, Divider, Form, Input, InputNumber, Modal, Popconfirm, Row, Select, Space, Spin, Switch, Table, Tabs, Tag, Typography, Upload, message } from 'antd';
import { BankOutlined, DeleteOutlined, EditOutlined, FileExcelOutlined, PlusOutlined, ReloadOutlined, SaveOutlined, UploadOutlined } from '@ant-design/icons';
import { settingsAPI } from '../services/api';
import MaterialSettings from '../components/MaterialSettings';
const { Title, Text } = Typography;

export default function Settings(){
  const [companyForm]=Form.useForm(); const [catalogForm]=Form.useForm();
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [syncing,setSyncing]=useState(false); const [importing,setImporting]=useState(false);
  const [provinces,setProvinces]=useState([]); const [communes,setCommunes]=useState([]); const [meta,setMeta]=useState(null);
  const [catalogTypes,setCatalogTypes]=useState([]); const [catalogType,setCatalogType]=useState('TASK_TYPE'); const [catalogs,setCatalogs]=useState([]); const [catalogLoading,setCatalogLoading]=useState(false); const [catalogModal,setCatalogModal]=useState(false); const [editingCatalog,setEditingCatalog]=useState(null);

  const loadCommunes=async code=>{ if(!code){setCommunes([]);return;} const r=await settingsAPI.getCommunes(code); setCommunes(r.data||[]); };
  const load=async()=>{setLoading(true);try{const [company,p,m,t]=await Promise.all([settingsAPI.getCompany(),settingsAPI.getProvinces(),settingsAPI.getAdministrativeMeta(),settingsAPI.getCatalogTypes()]);setProvinces(p.data||[]);setMeta(m.data);setCatalogTypes(t.data||[]);companyForm.setFieldsValue(company.data||{});await loadCommunes(company.data?.province_code);}catch(e){message.error(e.message);}finally{setLoading(false);}};
  const loadCatalogs=async(type=catalogType)=>{setCatalogLoading(true);try{const r=await settingsAPI.getCatalogs({type,include_inactive:true});setCatalogs(r.data||[]);}catch(e){message.error(e.message);}finally{setCatalogLoading(false);}};
  useEffect(()=>{load();},[]); useEffect(()=>{loadCatalogs(catalogType);},[catalogType]);
  const saveCompany=async values=>{setSaving(true);try{await settingsAPI.updateCompany(values);message.success('Đã lưu thông tin công ty');await load();}catch(e){message.error(e.message);}finally{setSaving(false);}};
  const sync=async()=>{setSyncing(true);try{const province=companyForm.getFieldValue('province_code');await settingsAPI.syncAdministrative(province?[province]:undefined);message.success('Đã cập nhật danh mục');await load();}catch(e){message.error(e.message);}finally{setSyncing(false);}};
  const importFile=async({file,onSuccess,onError})=>{setImporting(true);try{const r=await settingsAPI.importAdministrative(file);message.success(r.message||'Đã import');onSuccess?.(r);await load();}catch(e){message.error(e.message);onError?.(e);}finally{setImporting(false);}};
  const openCatalog=(item=null)=>{setEditingCatalog(item);catalogForm.resetFields();catalogForm.setFieldsValue(item||{catalog_type:catalogType,is_active:true,is_default:false,sort_order:0});setCatalogModal(true);};
  const saveCatalog=async values=>{try{if(editingCatalog)await settingsAPI.updateCatalog(editingCatalog.id,values);else await settingsAPI.createCatalog({...values,catalog_type:catalogType});message.success(editingCatalog?'Đã cập nhật danh mục':'Đã thêm danh mục');setCatalogModal(false);await loadCatalogs();}catch(e){message.error(e.message);}};
  const deleteCatalog=async id=>{try{await settingsAPI.deleteCatalog(id);message.success('Đã xóa danh mục');await loadCatalogs();}catch(e){message.error(e.message);}};
  const typeName=useMemo(()=>catalogTypes.find(x=>x.code===catalogType)?.name||catalogType,[catalogTypes,catalogType]);
  const columns=[{title:'Mã',dataIndex:'code',width:160},{title:'Tên',dataIndex:'name'},{title:'Mô tả',dataIndex:'description'},{title:'Thứ tự',dataIndex:'sort_order',width:90},{title:'Mặc định',dataIndex:'is_default',width:90,render:v=>v?<Tag color="blue">Có</Tag>:'-'},{title:'Trạng thái',dataIndex:'is_active',width:120,render:v=><Tag color={v?'green':'default'}>{v?'Hoạt động':'Không hoạt động'}</Tag>},{title:'Thao tác',width:150,render:(_,r)=><Space><Button icon={<EditOutlined/>} onClick={()=>openCatalog(r)}/><Popconfirm title="Xóa danh mục này?" onConfirm={()=>deleteCatalog(r.id)}><Button danger icon={<DeleteOutlined/>}/></Popconfirm></Space>}];

  return <div><Title level={2}><BankOutlined/> Cài đặt hệ thống</Title><Tabs items={[
    {key:'company',label:'Thông tin công ty',children:<Spin spinning={loading}><Card><Alert showIcon type="info" message="Địa chỉ hành chính 2 cấp" description="Chọn Tỉnh/Thành và Phường/Xã/Đặc khu; không sử dụng Quận/Huyện." style={{marginBottom:20}}/><Form form={companyForm} layout="vertical" onFinish={saveCompany}><Row gutter={16}><Col xs={24} md={12}><Form.Item name="company_name" label="Tên công ty" rules={[{required:true}]}><Input/></Form.Item></Col><Col xs={24} md={12}><Form.Item name="short_name" label="Tên viết tắt"><Input/></Form.Item></Col><Col xs={24} md={8}><Form.Item name="tax_code" label="Mã số thuế"><Input/></Form.Item></Col><Col xs={24} md={8}><Form.Item name="representative_name" label="Người đại diện"><Input/></Form.Item></Col><Col xs={24} md={8}><Form.Item name="phone" label="Điện thoại"><Input/></Form.Item></Col><Col xs={24} md={12}><Form.Item name="email" label="Email" rules={[{type:'email'}]}><Input/></Form.Item></Col><Col xs={24} md={12}><Form.Item name="website" label="Website"><Input/></Form.Item></Col><Col span={24}><Form.Item name="address_line" label="Số nhà, tên đường"><Input.TextArea rows={2}/></Form.Item></Col><Col xs={24} md={12}><Form.Item name="province_code" label="Tỉnh/Thành phố"><Select showSearch optionFilterProp="label" allowClear options={provinces.map(x=>({value:x.code,label:`${x.unit_type} ${x.name}`}))} onChange={v=>{companyForm.setFieldValue('commune_code',null);loadCommunes(v);}}/></Form.Item></Col><Col xs={24} md={12}><Form.Item name="commune_code" label="Phường/Xã/Đặc khu"><Select showSearch optionFilterProp="label" allowClear options={communes.map(x=>({value:x.code,label:`${x.unit_type} ${x.name}`}))}/></Form.Item></Col><Col xs={24} md={8}><Form.Item name="postal_code" label="Mã bưu chính"><Input/></Form.Item></Col><Col xs={24} md={8}><Form.Item name="timezone" label="Múi giờ"><Select options={[{value:'Asia/Ho_Chi_Minh',label:'Asia/Ho_Chi_Minh'}]}/></Form.Item></Col><Col xs={24} md={8}><Form.Item name="date_format" label="Định dạng ngày"><Select options={['DD/MM/YYYY','YYYY-MM-DD'].map(v=>({value:v,label:v}))}/></Form.Item></Col></Row><Button type="primary" htmlType="submit" icon={<SaveOutlined/>} loading={saving}>Lưu thông tin</Button></Form></Card></Spin>},
    {key:'catalogs',label:'Danh mục nghiệp vụ',children:<Card><Alert showIcon type="info" message="Danh mục dùng chung" description="Các danh mục đang hoạt động được dùng trực tiếp trong form Nhân viên, Nhiệm vụ và Lịch trình. Mục đã được sử dụng không thể xóa; hãy chuyển sang Không hoạt động."/><Divider/><Space wrap style={{marginBottom:16}}><Select value={catalogType} style={{width:240}} options={catalogTypes.map(x=>({value:x.code,label:x.name}))} onChange={setCatalogType}/><Button type="primary" icon={<PlusOutlined/>} onClick={()=>openCatalog()}>Thêm {typeName}</Button><Button icon={<ReloadOutlined/>} onClick={()=>loadCatalogs()}>Tải lại</Button></Space><Table rowKey="id" loading={catalogLoading} dataSource={catalogs} columns={columns} pagination={false}/></Card>},
    {key:'materials',label:'Vật tư & Kho',children:<MaterialSettings/>},
    {key:'administrative',label:'Danh mục hành chính',children:<Card><Alert showIcon type="warning" message="Import Excel là phương thức chính" description="File một bảng duy nhất gồm 5 cột, không sử dụng Quận/Huyện."/><Divider/><Descriptions bordered column={1} size="small"><Descriptions.Item label="Nguồn">{meta?.source_name||'-'}</Descriptions.Item><Descriptions.Item label="Tỉnh/Thành">{meta?.province_count??provinces.length}</Descriptions.Item><Descriptions.Item label="Phường/Xã/Đặc khu">{meta?.commune_count??0}</Descriptions.Item><Descriptions.Item label="Trạng thái">{meta?.sync_status||'-'} {meta?.sync_message&&`— ${meta.sync_message}`}</Descriptions.Item></Descriptions><Divider/><Space wrap><Upload accept=".xlsx" maxCount={1} showUploadList={false} customRequest={importFile}><Button type="primary" icon={<UploadOutlined/>} loading={importing}>Import Excel</Button></Upload><Button icon={<FileExcelOutlined/>} href="/administrative-import-template.xlsx" download>Tải file mẫu</Button><Button icon={<ReloadOutlined/>} loading={syncing} onClick={sync}>Thử đồng bộ trực tuyến</Button></Space><Divider/><Text type="secondary">Yêu cầu đúng 34 Tỉnh/Thành và 3.321 Phường/Xã/Đặc khu.</Text></Card>}
  ]}/><Modal title={editingCatalog?`Sửa ${typeName}`:`Thêm ${typeName}`} open={catalogModal} onCancel={()=>setCatalogModal(false)} footer={null}><Form form={catalogForm} layout="vertical" onFinish={saveCatalog}><Form.Item name="code" label="Mã" rules={[{required:!editingCatalog}]}><Input disabled={!!editingCatalog} placeholder="Tự tạo từ tên nếu để trống"/></Form.Item><Form.Item name="name" label="Tên" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="description" label="Mô tả"><Input.TextArea rows={2}/></Form.Item><Row gutter={16}><Col span={12}><Form.Item name="sort_order" label="Thứ tự"><InputNumber style={{width:'100%'}}/></Form.Item></Col><Col span={12}><Form.Item name="color" label="Màu hiển thị"><Input placeholder="blue hoặc #1677ff"/></Form.Item></Col></Row><Space><Form.Item name="is_default" label="Mặc định" valuePropName="checked"><Switch/></Form.Item><Form.Item name="is_active" label="Hoạt động" valuePropName="checked"><Switch/></Form.Item></Space><div><Button type="primary" htmlType="submit">Lưu</Button></div></Form></Modal></div>;
}
